### ISSUE TITLE
Bugs with the offset and limit parameters

### ISSUE THREAD

**Issue by jimtut** [svvitale/jira-missing-rest-api#1]
We've been using this API for over a year, and it has been a great way to pull all the users from JIRA at once (which we then use to look for new or deleted users, and update our mailing lists).

However, it doesn't appear as if the "offset" or "limit" parameters are being used.

In making a call like "/rest/missing/latest/users?limit=2000", the response looks like:
count: 1000
limit: 2000
offset: 0
users: (array of 1000 users)

If I remove the "limit=2000" parameter, I definitely only get 50 responses (the default), but there seems to be a max of 1000 somewhere (not something I can find in the code, so perhaps it's a limit in Atlassian?).

We only have 2000 users, so I could live with the limit of 1000 *IF* the offset param worked properly.  However, if I set that to 1000, I get no results.  If I set it 999, I get 1 result.

So, again, there seems to be some limit stopping at user #1000.  I can't see anything like that in the code, so I'm guessing there might be an Atlassian limit. [This page](https://community.atlassian.com/t5/Answers-Developer-Questions/How-to-get-more-than-50-issues-with-search-API/qaq-p/463122) seems to confirm that this might be so.  Can you confirm if there's anything that can be done in your API, or if I need to look into modifying server settings?  If there's nothing to be done in your code, could you update your Readme to indicate this limit?

**Comment by svvitale** [comment]
Nice to hear this is getting some use!  I think I can adjust the `UserSearchParams` structure to include a max results value.  I'll attempt this and let you know how it goes.  I may need you to test it against an instance with that many users (I don't have access to an instance with that many).

**Comment by jimtut** [comment]
Terrific, thanks!

**Comment by svvitale** [comment]
Hi Jim, try the beta release here: https://github.com/svvitale/jira-missing-rest-api/releases/tag/1.0.1beta

See if that works better for you.  If so, I'll go ahead and release 1.0.1 with this fix. I was able to test it up to 10000 users with good success.

**Comment by jimtut** [comment]
Perfect!

Before the 1.0.1 beta, by API calls gave me:

Total Users	1000
Confluence Users	880
JIRA Users	775

After the beta, I got:

Total Users	1318
Confluence Users	1163
JIRA Users	1017

Thanks, that worked great!
